In [1]:
import pandas as pd
import vivarium_inputs
import gbd_mapping

Config: 'input_data:
    cache_data:
        base: True
    intermediary_data_cache_path:
        base: /share/scratch/users/{username}/cache'
Cache Dir: '/share/scratch/users/zmbc/cache'

In [2]:
location = "india"
vehicle = "rice" # TODO: Check!
scenario = "intervention"

In [3]:
# Parameters
location = "nigeria"
vehicle = "bouillon"
scenario = "intervention"

In [4]:
def aggregate_by_scenario(df):
    return df.groupby(["scenario", "input_draw", "wealth_quintile"]).value.sum().groupby(["scenario", "wealth_quintile"]).mean()

In [5]:
pregnancy_ylls = (
    pd.read_parquet(f"0100_rescale_results/pregnancy_results/{location}/ylls.parquet")
)
pregnancy_ylls

,measure,entity_type,entity,sub_entity,age_group,anemia_status_at_birth,wealth_quintile,scenario,random_seed,input_draw,value
0,ylls,cause,maternal_disorders,maternal_disorders,10_to_14,invalid,lowest,baseline,32,0,0.0
1,ylls,cause,other_causes,other_causes,10_to_14,invalid,lowest,baseline,32,0,0.0
2,ylls,cause,maternal_disorders,maternal_disorders,10_to_14,invalid,second,baseline,32,0,0.0
3,ylls,cause,other_causes,other_causes,10_to_14,invalid,second,baseline,32,0,0.0
4,ylls,cause,maternal_disorders,maternal_disorders,10_to_14,invalid,middle,baseline,32,0,0.0
...,...,...,...,...,...,...,...,...,...,...,...
179995,ylls,cause,other_causes,other_causes,95_plus,severe,middle,intervention,60,0,0.0
179996,ylls,cause,maternal_disorders,maternal_disorders,95_plus,severe,fourth,intervention,60,0,0.0
179997,ylls,cause,other_causes,other_causes,95_plus,severe,fourth,intervention,60,0,0.0
179998,ylls,cause,maternal_disorders,maternal_disorders,95_plus,severe,highest,intervention,60,0,0.0
179999,ylls,cause,other_causes,other_causes,95_plus,severe,highest,intervention,60,0,0.0

In [6]:
pregnancy_ylls.groupby("scenario").random_seed.nunique()

scenario
baseline        100
intervention    100
Name: random_seed, dtype: int64

In [7]:
pregnancy_ylls_by_scenario = aggregate_by_scenario(pregnancy_ylls)
pregnancy_ylls_by_scenario

scenario      wealth_quintile
baseline      fourth             159369.249825
              highest            146485.741855
              lowest             243575.766544
              middle             194939.256420
              second             223397.331792
intervention  fourth             157851.246655
              highest            145759.042072
              lowest             239998.354605
              middle             193513.721170
              second             220001.680398
Name: value, dtype: float64

In [8]:
pregnancy_ylls_averted = pregnancy_ylls_by_scenario.loc["baseline"] - pregnancy_ylls_by_scenario.loc[scenario]
pregnancy_ylls_averted

wealth_quintile
fourth     1518.003170
highest     726.699783
lowest     3577.411939
middle     1425.535250
second     3395.651394
Name: value, dtype: float64

In [9]:
pregnancy_ylds = pd.read_parquet(f"0100_rescale_results/pregnancy_results/{location}/ylds.parquet")
pregnancy_ylds

,measure,entity_type,entity,sub_entity,age_group,anemia_status_at_birth,wealth_quintile,scenario,random_seed,input_draw,value
0,ylds,cause,all_causes,all_causes,10_to_14,invalid,lowest,baseline,32,0,1.897676
1,ylds,cause,pregnancy,pregnant,10_to_14,invalid,lowest,baseline,32,0,0.000000
2,ylds,cause,pregnancy,parturition,10_to_14,invalid,lowest,baseline,32,0,0.000000
3,ylds,cause,pregnancy,postpartum,10_to_14,invalid,lowest,baseline,32,0,0.000000
4,ylds,cause,maternal_disorders,maternal_disorders,10_to_14,invalid,lowest,baseline,32,0,0.000000
...,...,...,...,...,...,...,...,...,...,...,...
629995,ylds,cause,pregnancy,parturition,95_plus,severe,highest,intervention,60,0,0.000000
629996,ylds,cause,pregnancy,postpartum,95_plus,severe,highest,intervention,60,0,0.000000
629997,ylds,cause,maternal_disorders,maternal_disorders,95_plus,severe,highest,intervention,60,0,0.000000
629998,ylds,cause,maternal_hemorrhage,maternal_hemorrhage,95_plus,severe,highest,intervention,60,0,0.000000
629999,ylds,cause,anemia,anemia,95_plus,severe,highest,intervention,60,0,0.000000

In [10]:
pregnancy_ylds_by_scenario = aggregate_by_scenario(pregnancy_ylds)
pregnancy_ylds_by_scenario

scenario      wealth_quintile
baseline      fourth             21034.559554
              highest            15670.373751
              lowest             36974.336987
              middle             29964.217497
              second             42958.465616
intervention  fourth             20176.206435
              highest            15094.625825
              lowest             34780.402893
              middle             28556.473265
              second             40690.523208
Name: value, dtype: float64

In [11]:
pregnancy_ylds_averted = pregnancy_ylds_by_scenario.loc["baseline"] - pregnancy_ylds_by_scenario.loc[scenario]
pregnancy_ylds_averted

wealth_quintile
fourth      858.353120
highest     575.747926
lowest     2193.934094
middle     1407.744232
second     2267.942408
Name: value, dtype: float64

In [12]:
pregnancy_dalys_averted = pregnancy_ylls_averted + pregnancy_ylds_averted
pregnancy_dalys_averted

wealth_quintile
fourth     2376.356290
highest    1302.447709
lowest     5771.346033
middle     2833.279482
second     5663.593802
Name: value, dtype: float64

In [13]:
assert len(pd.read_parquet(f"0100_rescale_results/child_results/{location}/ylds.parquet")) == 0

In [14]:
child_ylls = pd.read_parquet(f"0100_rescale_results/child_results/{location}/ylls.parquet").rename(columns={"maternal_scenario": "scenario"})
child_ylls

,measure,entity_type,entity,sub_entity,age_group,sex,wealth_quintile,child_scenario,scenario,random_seed,input_draw,value
0,ylls,cause,stillborn,stillborn,0_to_6_months,Female,lowest,baseline,intervention,70,0,0.000000
1,ylls,cause,stillborn,stillborn,0_to_6_months,Female,second,baseline,intervention,70,0,0.000000
2,ylls,cause,stillborn,stillborn,0_to_6_months,Female,middle,baseline,intervention,70,0,0.000000
3,ylls,cause,stillborn,stillborn,0_to_6_months,Female,fourth,baseline,intervention,70,0,0.000000
4,ylls,cause,stillborn,stillborn,0_to_6_months,Female,highest,baseline,intervention,70,0,0.000000
...,...,...,...,...,...,...,...,...,...,...,...,...
15995,ylls,cause,other_causes,other_causes,18_to_59_months,Male,lowest,baseline,baseline,17,0,123371.091153
15996,ylls,cause,other_causes,other_causes,18_to_59_months,Male,second,baseline,baseline,17,0,127507.236963
15997,ylls,cause,other_causes,other_causes,18_to_59_months,Male,middle,baseline,baseline,17,0,94708.895448
15998,ylls,cause,other_causes,other_causes,18_to_59_months,Male,fourth,baseline,baseline,17,0,90392.920045
15999,ylls,cause,other_causes,other_causes,18_to_59_months,Male,highest,baseline,baseline,17,0,57785.435505

In [15]:
child_ylls_by_scenario = aggregate_by_scenario(child_ylls)
child_ylls_by_scenario

scenario      wealth_quintile
baseline      fourth             5.478970e+07
              highest            4.813209e+07
              lowest             8.153928e+07
              middle             6.799934e+07
              second             8.215571e+07
intervention  fourth             5.457043e+07
              highest            4.794673e+07
              lowest             8.060490e+07
              middle             6.757797e+07
              second             8.144905e+07
Name: value, dtype: float64

In [16]:
child_ylls_averted = child_ylls_by_scenario.loc["baseline"] - child_ylls_by_scenario.loc[scenario]
child_ylls_averted

wealth_quintile
fourth     219278.544733
highest    185360.093813
lowest     934381.351475
middle     421368.161545
second     706661.086533
Name: value, dtype: float64

In [17]:
f'{round(child_ylls_averted.sum()):,}'

'2,467,049'

In [18]:
child_days_averted = child_ylls_averted + 0

In [19]:
dalys_averted = pregnancy_dalys_averted + child_days_averted
dalys_averted

wealth_quintile
fourth     221654.901023
highest    186662.541522
lowest     940152.697508
middle     424201.441028
second     712324.680335
Name: value, dtype: float64

In [20]:
f'{round(dalys_averted.sum()):,}'

'2,484,996'