In [61]:
import pandas as pd
import vivarium_inputs
import gbd_mapping

In [62]:
location = "india"

In [63]:
def aggregate_by_scenario(df):
    return df.groupby(["scenario", "input_draw", "wealth_quintile"]).value.sum().groupby(["scenario", "wealth_quintile"]).mean()

In [64]:
pregnancy_ylls = (
    pd.read_parquet(f"0100_rescale_results/pregnancy_results/{location}/ylls.parquet")
)
pregnancy_ylls

,measure,entity_type,entity,sub_entity,age_group,wealth_quintile,scenario,random_seed,input_draw,value
0,ylls,cause,maternal_disorders,maternal_disorders,10_to_14,lowest,baseline,5,0,0.0
1,ylls,cause,other_causes,other_causes,10_to_14,lowest,baseline,5,0,0.0
2,ylls,cause,maternal_disorders,maternal_disorders,10_to_14,second,baseline,5,0,0.0
3,ylls,cause,other_causes,other_causes,10_to_14,second,baseline,5,0,0.0
4,ylls,cause,maternal_disorders,maternal_disorders,10_to_14,middle,baseline,5,0,0.0
...,...,...,...,...,...,...,...,...,...,...
7195,ylls,cause,other_causes,other_causes,95_plus,middle,baseline,9,0,0.0
7196,ylls,cause,maternal_disorders,maternal_disorders,95_plus,fourth,baseline,9,0,0.0
7197,ylls,cause,other_causes,other_causes,95_plus,fourth,baseline,9,0,0.0
7198,ylls,cause,maternal_disorders,maternal_disorders,95_plus,highest,baseline,9,0,0.0
7199,ylls,cause,other_causes,other_causes,95_plus,highest,baseline,9,0,0.0

In [65]:
pregnancy_ylls_by_scenario = aggregate_by_scenario(pregnancy_ylls)
pregnancy_ylls_by_scenario

scenario      wealth_quintile
baseline      fourth             140541.509478
              highest             75192.266914
              lowest             306857.185883
              middle             257931.746084
              second             187705.707148
intervention  fourth             140541.509478
              highest             75192.266914
              lowest             304748.561859
              middle             255709.183694
              second             187705.707148
Name: value, dtype: float64

In [66]:
pregnancy_ylls_averted = pregnancy_ylls_by_scenario.loc["baseline"] - pregnancy_ylls_by_scenario.loc["intervention"]
pregnancy_ylls_averted

wealth_quintile
fourth        0.000000
highest       0.000000
lowest     2108.624024
middle     2222.562390
second        0.000000
Name: value, dtype: float64

In [67]:
pregnancy_ylds = pd.read_parquet(f"0100_rescale_results/pregnancy_results/{location}/ylds.parquet")
pregnancy_ylds

,measure,entity_type,entity,sub_entity,age_group,wealth_quintile,scenario,random_seed,input_draw,value
0,ylds,cause,all_causes,all_causes,10_to_14,lowest,baseline,5,0,6.567339
1,ylds,cause,pregnancy,pregnant,10_to_14,lowest,baseline,5,0,0.000000
2,ylds,cause,pregnancy,parturition,10_to_14,lowest,baseline,5,0,0.000000
3,ylds,cause,pregnancy,postpartum,10_to_14,lowest,baseline,5,0,0.000000
4,ylds,cause,maternal_disorders,maternal_disorders,10_to_14,lowest,baseline,5,0,0.000000
...,...,...,...,...,...,...,...,...,...,...
25195,ylds,cause,pregnancy,parturition,95_plus,highest,baseline,9,0,0.000000
25196,ylds,cause,pregnancy,postpartum,95_plus,highest,baseline,9,0,0.000000
25197,ylds,cause,maternal_disorders,maternal_disorders,95_plus,highest,baseline,9,0,0.000000
25198,ylds,cause,maternal_hemorrhage,maternal_hemorrhage,95_plus,highest,baseline,9,0,0.000000
25199,ylds,cause,anemia,anemia,95_plus,highest,baseline,9,0,0.000000

In [68]:
pregnancy_ylds_by_scenario = aggregate_by_scenario(pregnancy_ylds)
pregnancy_ylds_by_scenario

scenario      wealth_quintile
baseline      fourth              64337.346182
              highest             43730.953404
              lowest             109692.184691
              middle              81092.505939
              second              96261.424237
intervention  fourth              63093.746199
              highest             42787.130025
              lowest             108124.379245
              middle              79843.190534
              second              94957.103564
Name: value, dtype: float64

In [69]:
pregnancy_ylds_averted = pregnancy_ylds_by_scenario.loc["baseline"] - pregnancy_ylds_by_scenario.loc["intervention"]
pregnancy_ylds_averted

wealth_quintile
fourth     1243.599983
highest     943.823380
lowest     1567.805446
middle     1249.315405
second     1304.320673
Name: value, dtype: float64

In [70]:
pregnancy_dalys_averted = pregnancy_ylls_averted + pregnancy_ylds_averted
pregnancy_dalys_averted

wealth_quintile
fourth     1243.599983
highest     943.823380
lowest     3676.429470
middle     3471.877795
second     1304.320673
Name: value, dtype: float64

In [71]:
assert len(pd.read_parquet(f"0100_rescale_results/child_results/{location}/ylds.parquet")) == 0

In [72]:
child_ylls = pd.read_parquet(f"0100_rescale_results/child_results/{location}/ylls.parquet").rename(columns={"maternal_scenario": "scenario"})
child_ylls

,measure,entity_type,entity,sub_entity,age_group,sex,wealth_quintile,child_scenario,scenario,random_seed,input_draw,value
0,ylls,cause,stillborn,stillborn,0_to_6_months,Female,lowest,baseline,baseline,0,0,0.000000
1,ylls,cause,stillborn,stillborn,0_to_6_months,Female,second,baseline,baseline,0,0,0.000000
2,ylls,cause,stillborn,stillborn,0_to_6_months,Female,middle,baseline,baseline,0,0,0.000000
3,ylls,cause,stillborn,stillborn,0_to_6_months,Female,fourth,baseline,baseline,0,0,0.000000
4,ylls,cause,stillborn,stillborn,0_to_6_months,Female,highest,baseline,baseline,0,0,0.000000
...,...,...,...,...,...,...,...,...,...,...,...,...
3195,ylls,cause,other_causes,other_causes,18_to_59_months,Male,lowest,baseline,baseline,10,0,201646.407216
3196,ylls,cause,other_causes,other_causes,18_to_59_months,Male,second,baseline,baseline,10,0,168356.943702
3197,ylls,cause,other_causes,other_causes,18_to_59_months,Male,middle,baseline,baseline,10,0,166576.083724
3198,ylls,cause,other_causes,other_causes,18_to_59_months,Male,fourth,baseline,baseline,10,0,201030.314094
3199,ylls,cause,other_causes,other_causes,18_to_59_months,Male,highest,baseline,baseline,10,0,134178.060957

In [73]:
child_ylls_by_scenario = aggregate_by_scenario(child_ylls)
child_ylls_by_scenario

scenario      wealth_quintile
baseline      fourth             6.259638e+07
              highest            5.689323e+07
              lowest             8.770240e+07
              middle             7.433765e+07
              second             7.815284e+07
intervention  fourth             5.420174e+07
              highest            4.620669e+07
              lowest             7.871727e+07
              middle             6.615107e+07
              second             7.086814e+07
Name: value, dtype: float64

In [75]:
child_ylls_averted = child_ylls_by_scenario.loc["baseline"] - child_ylls_by_scenario.loc["intervention"]
child_ylls_averted

wealth_quintile
fourth     8.394648e+06
highest    1.068654e+07
lowest     8.985136e+06
middle     8.186578e+06
second     7.284701e+06
Name: value, dtype: float64

In [81]:
f'{round(child_ylls_averted.sum()):,}'

'43,537,601'

In [76]:
child_days_averted = child_ylls_averted + 0

In [77]:
dalys_averted = pregnancy_dalys_averted + child_days_averted
dalys_averted

wealth_quintile
fourth     8.395892e+06
highest    1.068748e+07
lowest     8.988813e+06
middle     8.190050e+06
second     7.286005e+06
Name: value, dtype: float64

In [82]:
f'{round(dalys_averted.sum()):,}'

'43,548,241'