In [1]:
import pandas as pd
import vivarium_inputs
import gbd_mapping

Config: 'input_data:
    cache_data:
        base: True
    intermediary_data_cache_path:
        base: /share/scratch/users/{username}/cache'
Cache Dir: '/share/scratch/users/zmbc/cache'

In [2]:
location = "india"

In [3]:
# Parameters
location = "india"

In [4]:
def aggregate_by_scenario(df):
    return df.groupby(["scenario", "input_draw", "wealth_quintile"]).value.sum().groupby(["scenario", "wealth_quintile"]).mean()

In [5]:
pregnancy_ylls = (
    pd.read_parquet(f"0100_rescale_results/pregnancy_results/{location}/ylls.parquet")
)
pregnancy_ylls

,measure,entity_type,entity,sub_entity,age_group,anemia_status_at_birth,wealth_quintile,scenario,random_seed,input_draw,value
0,ylls,cause,maternal_disorders,maternal_disorders,10_to_14,invalid,lowest,intervention,73,0,0.0
1,ylls,cause,other_causes,other_causes,10_to_14,invalid,lowest,intervention,73,0,0.0
2,ylls,cause,maternal_disorders,maternal_disorders,10_to_14,invalid,second,intervention,73,0,0.0
3,ylls,cause,other_causes,other_causes,10_to_14,invalid,second,intervention,73,0,0.0
4,ylls,cause,maternal_disorders,maternal_disorders,10_to_14,invalid,middle,intervention,73,0,0.0
...,...,...,...,...,...,...,...,...,...,...,...
179995,ylls,cause,other_causes,other_causes,95_plus,severe,middle,intervention,55,0,0.0
179996,ylls,cause,maternal_disorders,maternal_disorders,95_plus,severe,fourth,intervention,55,0,0.0
179997,ylls,cause,other_causes,other_causes,95_plus,severe,fourth,intervention,55,0,0.0
179998,ylls,cause,maternal_disorders,maternal_disorders,95_plus,severe,highest,intervention,55,0,0.0
179999,ylls,cause,other_causes,other_causes,95_plus,severe,highest,intervention,55,0,0.0

In [6]:
pregnancy_ylls.groupby("scenario").random_seed.nunique()

scenario
baseline        100
intervention    100
Name: random_seed, dtype: int64

In [7]:
pregnancy_ylls_by_scenario = aggregate_by_scenario(pregnancy_ylls)
pregnancy_ylls_by_scenario

scenario      wealth_quintile
baseline      fourth             190084.512332
              highest            182093.596928
              lowest             284595.585068
              middle             183665.499160
              second             208846.426642
intervention  fourth             187706.080219
              highest            180905.102948
              lowest             281919.549747
              middle             182246.157737
              second             207296.858775
Name: value, dtype: float64

In [8]:
pregnancy_ylls_averted = pregnancy_ylls_by_scenario.loc["baseline"] - pregnancy_ylls_by_scenario.loc["intervention"]
pregnancy_ylls_averted

wealth_quintile
fourth     2378.432114
highest    1188.493981
lowest     2676.035321
middle     1419.341423
second     1549.567867
Name: value, dtype: float64

In [9]:
pregnancy_ylds = pd.read_parquet(f"0100_rescale_results/pregnancy_results/{location}/ylds.parquet")
pregnancy_ylds

,measure,entity_type,entity,sub_entity,age_group,anemia_status_at_birth,wealth_quintile,scenario,random_seed,input_draw,value
0,ylds,cause,all_causes,all_causes,10_to_14,invalid,lowest,intervention,73,0,0.672643
1,ylds,cause,pregnancy,pregnant,10_to_14,invalid,lowest,intervention,73,0,0.000000
2,ylds,cause,pregnancy,parturition,10_to_14,invalid,lowest,intervention,73,0,0.000000
3,ylds,cause,pregnancy,postpartum,10_to_14,invalid,lowest,intervention,73,0,0.000000
4,ylds,cause,maternal_disorders,maternal_disorders,10_to_14,invalid,lowest,intervention,73,0,0.000000
...,...,...,...,...,...,...,...,...,...,...,...
629995,ylds,cause,pregnancy,parturition,95_plus,severe,highest,intervention,55,0,0.000000
629996,ylds,cause,pregnancy,postpartum,95_plus,severe,highest,intervention,55,0,0.000000
629997,ylds,cause,maternal_disorders,maternal_disorders,95_plus,severe,highest,intervention,55,0,0.000000
629998,ylds,cause,maternal_hemorrhage,maternal_hemorrhage,95_plus,severe,highest,intervention,55,0,0.000000
629999,ylds,cause,anemia,anemia,95_plus,severe,highest,intervention,55,0,0.000000

In [10]:
pregnancy_ylds_by_scenario = aggregate_by_scenario(pregnancy_ylds)
pregnancy_ylds_by_scenario

scenario      wealth_quintile
baseline      fourth              62504.633514
              highest             45982.125105
              lowest             117635.106168
              middle              75238.328615
              second              93419.728225
intervention  fourth              60866.095388
              highest             44469.551419
              lowest             115143.315809
              middle              73478.619784
              second              91558.336429
Name: value, dtype: float64

In [11]:
pregnancy_ylds_averted = pregnancy_ylds_by_scenario.loc["baseline"] - pregnancy_ylds_by_scenario.loc["intervention"]
pregnancy_ylds_averted

wealth_quintile
fourth     1638.538126
highest    1512.573686
lowest     2491.790360
middle     1759.708831
second     1861.391795
Name: value, dtype: float64

In [12]:
pregnancy_dalys_averted = pregnancy_ylls_averted + pregnancy_ylds_averted
pregnancy_dalys_averted

wealth_quintile
fourth     4016.970239
highest    2701.067666
lowest     5167.825681
middle     3179.050254
second     3410.959663
Name: value, dtype: float64

In [13]:
assert len(pd.read_parquet(f"0100_rescale_results/child_results/{location}/ylds.parquet")) == 0

In [14]:
child_ylls = pd.read_parquet(f"0100_rescale_results/child_results/{location}/ylls.parquet").rename(columns={"maternal_scenario": "scenario"})
child_ylls

,measure,entity_type,entity,sub_entity,age_group,sex,wealth_quintile,child_scenario,scenario,random_seed,input_draw,value
0,ylls,cause,stillborn,stillborn,0_to_6_months,Female,lowest,baseline,intervention,66,0,0.000000
1,ylls,cause,stillborn,stillborn,0_to_6_months,Female,second,baseline,intervention,66,0,0.000000
2,ylls,cause,stillborn,stillborn,0_to_6_months,Female,middle,baseline,intervention,66,0,0.000000
3,ylls,cause,stillborn,stillborn,0_to_6_months,Female,fourth,baseline,intervention,66,0,0.000000
4,ylls,cause,stillborn,stillborn,0_to_6_months,Female,highest,baseline,intervention,66,0,0.000000
...,...,...,...,...,...,...,...,...,...,...,...,...
15995,ylls,cause,other_causes,other_causes,18_to_59_months,Male,lowest,baseline,baseline,35,0,27088.843459
15996,ylls,cause,other_causes,other_causes,18_to_59_months,Male,second,baseline,baseline,35,0,53918.940289
15997,ylls,cause,other_causes,other_causes,18_to_59_months,Male,middle,baseline,baseline,35,0,20058.797831
15998,ylls,cause,other_causes,other_causes,18_to_59_months,Male,fourth,baseline,baseline,35,0,13459.750482
15999,ylls,cause,other_causes,other_causes,18_to_59_months,Male,highest,baseline,baseline,35,0,26743.841840

In [15]:
child_ylls_by_scenario = aggregate_by_scenario(child_ylls)
child_ylls_by_scenario

scenario      wealth_quintile
baseline      fourth             6.345954e+07
              highest            6.141712e+07
              lowest             9.148467e+07
              middle             6.780176e+07
              second             7.595901e+07
intervention  fourth             6.291161e+07
              highest            6.094496e+07
              lowest             9.048529e+07
              middle             6.735067e+07
              second             7.541777e+07
Name: value, dtype: float64

In [16]:
child_ylls_averted = child_ylls_by_scenario.loc["baseline"] - child_ylls_by_scenario.loc["intervention"]
child_ylls_averted

wealth_quintile
fourth     547927.831056
highest    472162.182066
lowest     999379.530390
middle     451097.465585
second     541241.315522
Name: value, dtype: float64

In [17]:
f'{round(child_ylls_averted.sum()):,}'

'3,011,808'

In [18]:
child_days_averted = child_ylls_averted + 0

In [19]:
dalys_averted = pregnancy_dalys_averted + child_days_averted
dalys_averted

wealth_quintile
fourth     5.519448e+05
highest    4.748632e+05
lowest     1.004547e+06
middle     4.542765e+05
second     5.446523e+05
Name: value, dtype: float64

In [20]:
f'{round(dalys_averted.sum()):,}'

'3,030,284'