In [1]:
import pandas as pd
import vivarium_inputs
import gbd_mapping

Config: 'input_data:
    cache_data:
        base: True
    intermediary_data_cache_path:
        base: /share/scratch/users/{username}/cache'
Cache Dir: '/share/scratch/users/zmbc/cache'

In [2]:
location = "india"

In [3]:
# Parameters
location = "india"

In [4]:
def aggregate_by_scenario(df):
    return df.groupby(["scenario", "input_draw", "wealth_quintile"]).value.sum().groupby(["scenario", "wealth_quintile"]).mean()

In [5]:
pregnancy_ylls = (
    pd.read_parquet(f"0100_rescale_results/pregnancy_results/{location}/ylls.parquet")
)
pregnancy_ylls

,measure,entity_type,entity,sub_entity,age_group,anemia_status_at_birth,wealth_quintile,scenario,random_seed,input_draw,value
0,ylls,cause,maternal_disorders,maternal_disorders,10_to_14,invalid,lowest,intervention,1,0,0.0
1,ylls,cause,other_causes,other_causes,10_to_14,invalid,lowest,intervention,1,0,0.0
2,ylls,cause,maternal_disorders,maternal_disorders,10_to_14,invalid,second,intervention,1,0,0.0
3,ylls,cause,other_causes,other_causes,10_to_14,invalid,second,intervention,1,0,0.0
4,ylls,cause,maternal_disorders,maternal_disorders,10_to_14,invalid,middle,intervention,1,0,0.0
...,...,...,...,...,...,...,...,...,...,...,...
35995,ylls,cause,other_causes,other_causes,95_plus,severe,middle,baseline,11,0,0.0
35996,ylls,cause,maternal_disorders,maternal_disorders,95_plus,severe,fourth,baseline,11,0,0.0
35997,ylls,cause,other_causes,other_causes,95_plus,severe,fourth,baseline,11,0,0.0
35998,ylls,cause,maternal_disorders,maternal_disorders,95_plus,severe,highest,baseline,11,0,0.0
35999,ylls,cause,other_causes,other_causes,95_plus,severe,highest,baseline,11,0,0.0

In [6]:
pregnancy_ylls_by_scenario = aggregate_by_scenario(pregnancy_ylls)
pregnancy_ylls_by_scenario

scenario      wealth_quintile
baseline      fourth             140541.509478
              highest             75192.266914
              lowest             306857.185883
              middle             257931.746084
              second             187705.707148
intervention  fourth             140541.509478
              highest             75192.266914
              lowest             304748.561859
              middle             255709.183694
              second             187705.707148
Name: value, dtype: float64

In [7]:
pregnancy_ylls_averted = pregnancy_ylls_by_scenario.loc["baseline"] - pregnancy_ylls_by_scenario.loc["intervention"]
pregnancy_ylls_averted

wealth_quintile
fourth        0.000000
highest       0.000000
lowest     2108.624024
middle     2222.562390
second        0.000000
Name: value, dtype: float64

In [8]:
pregnancy_ylds = pd.read_parquet(f"0100_rescale_results/pregnancy_results/{location}/ylds.parquet")
pregnancy_ylds

,measure,entity_type,entity,sub_entity,age_group,anemia_status_at_birth,wealth_quintile,scenario,random_seed,input_draw,value
0,ylds,cause,all_causes,all_causes,10_to_14,invalid,lowest,intervention,1,0,2.685219
1,ylds,cause,pregnancy,pregnant,10_to_14,invalid,lowest,intervention,1,0,0.000000
2,ylds,cause,pregnancy,parturition,10_to_14,invalid,lowest,intervention,1,0,0.000000
3,ylds,cause,pregnancy,postpartum,10_to_14,invalid,lowest,intervention,1,0,0.000000
4,ylds,cause,maternal_disorders,maternal_disorders,10_to_14,invalid,lowest,intervention,1,0,0.000000
...,...,...,...,...,...,...,...,...,...,...,...
125995,ylds,cause,pregnancy,parturition,95_plus,severe,highest,baseline,11,0,0.000000
125996,ylds,cause,pregnancy,postpartum,95_plus,severe,highest,baseline,11,0,0.000000
125997,ylds,cause,maternal_disorders,maternal_disorders,95_plus,severe,highest,baseline,11,0,0.000000
125998,ylds,cause,maternal_hemorrhage,maternal_hemorrhage,95_plus,severe,highest,baseline,11,0,0.000000
125999,ylds,cause,anemia,anemia,95_plus,severe,highest,baseline,11,0,0.000000

In [9]:
pregnancy_ylds_by_scenario = aggregate_by_scenario(pregnancy_ylds)
pregnancy_ylds_by_scenario

scenario      wealth_quintile
baseline      fourth              64337.346182
              highest             43730.953404
              lowest             109692.184691
              middle              81092.505939
              second              96261.424237
intervention  fourth              63093.746199
              highest             42787.130025
              lowest             108124.379245
              middle              79843.190534
              second              94957.103564
Name: value, dtype: float64

In [10]:
pregnancy_ylds_averted = pregnancy_ylds_by_scenario.loc["baseline"] - pregnancy_ylds_by_scenario.loc["intervention"]
pregnancy_ylds_averted

wealth_quintile
fourth     1243.599983
highest     943.823380
lowest     1567.805446
middle     1249.315405
second     1304.320673
Name: value, dtype: float64

In [11]:
pregnancy_dalys_averted = pregnancy_ylls_averted + pregnancy_ylds_averted
pregnancy_dalys_averted

wealth_quintile
fourth     1243.599983
highest     943.823380
lowest     3676.429470
middle     3471.877795
second     1304.320673
Name: value, dtype: float64

In [12]:
assert len(pd.read_parquet(f"0100_rescale_results/child_results/{location}/ylds.parquet")) == 0

In [13]:
child_ylls = pd.read_parquet(f"0100_rescale_results/child_results/{location}/ylls.parquet").rename(columns={"maternal_scenario": "scenario"})
child_ylls

,measure,entity_type,entity,sub_entity,age_group,sex,wealth_quintile,child_scenario,scenario,random_seed,input_draw,value
0,ylls,cause,stillborn,stillborn,0_to_6_months,Female,lowest,baseline,intervention,18,0,0.000000
1,ylls,cause,stillborn,stillborn,0_to_6_months,Female,second,baseline,intervention,18,0,0.000000
2,ylls,cause,stillborn,stillborn,0_to_6_months,Female,middle,baseline,intervention,18,0,0.000000
3,ylls,cause,stillborn,stillborn,0_to_6_months,Female,fourth,baseline,intervention,18,0,0.000000
4,ylls,cause,stillborn,stillborn,0_to_6_months,Female,highest,baseline,intervention,18,0,0.000000
...,...,...,...,...,...,...,...,...,...,...,...,...
3195,ylls,cause,other_causes,other_causes,18_to_59_months,Male,lowest,baseline,intervention,6,0,202693.941768
3196,ylls,cause,other_causes,other_causes,18_to_59_months,Male,second,baseline,intervention,6,0,200826.398986
3197,ylls,cause,other_causes,other_causes,18_to_59_months,Male,middle,baseline,intervention,6,0,66973.167656
3198,ylls,cause,other_causes,other_causes,18_to_59_months,Male,fourth,baseline,intervention,6,0,66350.208975
3199,ylls,cause,other_causes,other_causes,18_to_59_months,Male,highest,baseline,intervention,6,0,102142.346682

In [14]:
child_ylls_by_scenario = aggregate_by_scenario(child_ylls)
child_ylls_by_scenario

scenario      wealth_quintile
baseline      fourth             6.259638e+07
              highest            5.689323e+07
              lowest             8.770240e+07
              middle             7.433765e+07
              second             7.815284e+07
intervention  fourth             6.224949e+07
              highest            5.651038e+07
              lowest             8.728618e+07
              middle             7.395610e+07
              second             7.787532e+07
Name: value, dtype: float64

In [15]:
child_ylls_averted = child_ylls_by_scenario.loc["baseline"] - child_ylls_by_scenario.loc["intervention"]
child_ylls_averted

wealth_quintile
fourth     346897.089329
highest    382842.757279
lowest     416225.533252
middle     381555.309135
second     277518.157081
Name: value, dtype: float64

In [16]:
f'{round(child_ylls_averted.sum()):,}'

'1,805,039'

In [17]:
child_days_averted = child_ylls_averted + 0

In [18]:
dalys_averted = pregnancy_dalys_averted + child_days_averted
dalys_averted

wealth_quintile
fourth     348140.689312
highest    383786.580658
lowest     419901.962722
middle     385027.186930
second     278822.477754
Name: value, dtype: float64

In [19]:
f'{round(dalys_averted.sum()):,}'

'1,815,679'