In [1]:
import pandas as pd
import vivarium_inputs
import gbd_mapping

Config: 'input_data:
    cache_data:
        base: True
    intermediary_data_cache_path:
        base: /share/scratch/users/{username}/cache'
Cache Dir: '/share/scratch/users/zmbc/cache'

In [2]:
location = "india"

In [3]:
# Parameters
location = "nigeria"

In [4]:
def aggregate_by_scenario(df):
    return df.groupby(["scenario", "input_draw", "wealth_quintile"]).value.sum().groupby(["scenario", "wealth_quintile"]).mean()

In [5]:
pregnancy_ylls = (
    pd.read_parquet(f"0100_rescale_results/pregnancy_results/{location}/ylls.parquet")
)
pregnancy_ylls

,measure,entity_type,entity,sub_entity,age_group,anemia_status_at_birth,wealth_quintile,scenario,random_seed,input_draw,value
0,ylls,cause,maternal_disorders,maternal_disorders,10_to_14,invalid,lowest,intervention,44,0,0.0
1,ylls,cause,other_causes,other_causes,10_to_14,invalid,lowest,intervention,44,0,0.0
2,ylls,cause,maternal_disorders,maternal_disorders,10_to_14,invalid,second,intervention,44,0,0.0
3,ylls,cause,other_causes,other_causes,10_to_14,invalid,second,intervention,44,0,0.0
4,ylls,cause,maternal_disorders,maternal_disorders,10_to_14,invalid,middle,intervention,44,0,0.0
...,...,...,...,...,...,...,...,...,...,...,...
179995,ylls,cause,other_causes,other_causes,95_plus,severe,middle,baseline,52,0,0.0
179996,ylls,cause,maternal_disorders,maternal_disorders,95_plus,severe,fourth,baseline,52,0,0.0
179997,ylls,cause,other_causes,other_causes,95_plus,severe,fourth,baseline,52,0,0.0
179998,ylls,cause,maternal_disorders,maternal_disorders,95_plus,severe,highest,baseline,52,0,0.0
179999,ylls,cause,other_causes,other_causes,95_plus,severe,highest,baseline,52,0,0.0

In [6]:
pregnancy_ylls.groupby("scenario").random_seed.nunique()

scenario
baseline        100
intervention    100
Name: random_seed, dtype: int64

In [7]:
pregnancy_ylls_by_scenario = aggregate_by_scenario(pregnancy_ylls)
pregnancy_ylls_by_scenario

scenario      wealth_quintile
baseline      fourth             153961.215648
              highest            100973.094735
              lowest             270539.863941
              middle             172682.847837
              second             251820.954557
intervention  fourth             152451.361306
              highest             99665.624512
              lowest             267700.928295
              middle             170834.582929
              second             248962.430773
Name: value, dtype: float64

In [8]:
pregnancy_ylls_averted = pregnancy_ylls_by_scenario.loc["baseline"] - pregnancy_ylls_by_scenario.loc["intervention"]
pregnancy_ylls_averted

wealth_quintile
fourth     1509.854342
highest    1307.470223
lowest     2838.935646
middle     1848.264908
second     2858.523784
Name: value, dtype: float64

In [9]:
pregnancy_ylds = pd.read_parquet(f"0100_rescale_results/pregnancy_results/{location}/ylds.parquet")
pregnancy_ylds

,measure,entity_type,entity,sub_entity,age_group,anemia_status_at_birth,wealth_quintile,scenario,random_seed,input_draw,value
0,ylds,cause,all_causes,all_causes,10_to_14,invalid,lowest,intervention,44,0,1.572877
1,ylds,cause,pregnancy,pregnant,10_to_14,invalid,lowest,intervention,44,0,0.000000
2,ylds,cause,pregnancy,parturition,10_to_14,invalid,lowest,intervention,44,0,0.000000
3,ylds,cause,pregnancy,postpartum,10_to_14,invalid,lowest,intervention,44,0,0.000000
4,ylds,cause,maternal_disorders,maternal_disorders,10_to_14,invalid,lowest,intervention,44,0,0.000000
...,...,...,...,...,...,...,...,...,...,...,...
629995,ylds,cause,pregnancy,parturition,95_plus,severe,highest,baseline,52,0,0.000000
629996,ylds,cause,pregnancy,postpartum,95_plus,severe,highest,baseline,52,0,0.000000
629997,ylds,cause,maternal_disorders,maternal_disorders,95_plus,severe,highest,baseline,52,0,0.000000
629998,ylds,cause,maternal_hemorrhage,maternal_hemorrhage,95_plus,severe,highest,baseline,52,0,0.000000
629999,ylds,cause,anemia,anemia,95_plus,severe,highest,baseline,52,0,0.000000

In [10]:
pregnancy_ylds_by_scenario = aggregate_by_scenario(pregnancy_ylds)
pregnancy_ylds_by_scenario

scenario      wealth_quintile
baseline      fourth             21010.637309
              highest            15378.654163
              lowest             37037.515270
              middle             30006.936180
              second             43147.632830
intervention  fourth             19829.427613
              highest            14684.083476
              lowest             34029.376745
              middle             27903.427946
              second             39749.157588
Name: value, dtype: float64

In [11]:
pregnancy_ylds_averted = pregnancy_ylds_by_scenario.loc["baseline"] - pregnancy_ylds_by_scenario.loc["intervention"]
pregnancy_ylds_averted

wealth_quintile
fourth     1181.209695
highest     694.570687
lowest     3008.138525
middle     2103.508234
second     3398.475242
Name: value, dtype: float64

In [12]:
pregnancy_dalys_averted = pregnancy_ylls_averted + pregnancy_ylds_averted
pregnancy_dalys_averted

wealth_quintile
fourth     2691.064037
highest    2002.040910
lowest     5847.074171
middle     3951.773142
second     6256.999026
Name: value, dtype: float64

In [13]:
assert len(pd.read_parquet(f"0100_rescale_results/child_results/{location}/ylds.parquet")) == 0

In [14]:
child_ylls = pd.read_parquet(f"0100_rescale_results/child_results/{location}/ylls.parquet").rename(columns={"maternal_scenario": "scenario"})
child_ylls

,measure,entity_type,entity,sub_entity,age_group,sex,wealth_quintile,child_scenario,scenario,random_seed,input_draw,value
0,ylls,cause,stillborn,stillborn,0_to_6_months,Female,lowest,baseline,intervention,51,0,0.000000
1,ylls,cause,stillborn,stillborn,0_to_6_months,Female,second,baseline,intervention,51,0,0.000000
2,ylls,cause,stillborn,stillborn,0_to_6_months,Female,middle,baseline,intervention,51,0,0.000000
3,ylls,cause,stillborn,stillborn,0_to_6_months,Female,fourth,baseline,intervention,51,0,0.000000
4,ylls,cause,stillborn,stillborn,0_to_6_months,Female,highest,baseline,intervention,51,0,0.000000
...,...,...,...,...,...,...,...,...,...,...,...,...
15995,ylls,cause,other_causes,other_causes,18_to_59_months,Male,lowest,baseline,intervention,43,0,98619.079939
15996,ylls,cause,other_causes,other_causes,18_to_59_months,Male,second,baseline,intervention,43,0,117063.872490
15997,ylls,cause,other_causes,other_causes,18_to_59_months,Male,middle,baseline,intervention,43,0,96671.172790
15998,ylls,cause,other_causes,other_causes,18_to_59_months,Male,fourth,baseline,intervention,43,0,96549.991925
15999,ylls,cause,other_causes,other_causes,18_to_59_months,Male,highest,baseline,intervention,43,0,94579.021368

In [15]:
child_ylls_by_scenario = aggregate_by_scenario(child_ylls)
child_ylls_by_scenario

scenario      wealth_quintile
baseline      fourth             5.483179e+07
              highest            4.833931e+07
              lowest             8.156857e+07
              middle             6.788913e+07
              second             8.182894e+07
intervention  fourth             5.453368e+07
              highest            4.810295e+07
              lowest             8.049379e+07
              middle             6.733119e+07
              second             8.089924e+07
Name: value, dtype: float64

In [16]:
child_ylls_averted = child_ylls_by_scenario.loc["baseline"] - child_ylls_by_scenario.loc["intervention"]
child_ylls_averted

wealth_quintile
fourth     2.981072e+05
highest    2.363644e+05
lowest     1.074775e+06
middle     5.579432e+05
second     9.297002e+05
Name: value, dtype: float64

In [17]:
f'{round(child_ylls_averted.sum()):,}'

'3,096,890'

In [18]:
child_days_averted = child_ylls_averted + 0

In [19]:
dalys_averted = pregnancy_dalys_averted + child_days_averted
dalys_averted

wealth_quintile
fourth     3.007982e+05
highest    2.383665e+05
lowest     1.080623e+06
middle     5.618950e+05
second     9.359572e+05
Name: value, dtype: float64

In [20]:
f'{round(dalys_averted.sum()):,}'

'3,117,639'