In [1]:
import pandas as pd
import vivarium_inputs
import gbd_mapping

Config: 'input_data:
    cache_data:
        base: True
    intermediary_data_cache_path:
        base: /share/scratch/users/{username}/cache'
Cache Dir: '/share/scratch/users/zmbc/cache'

In [2]:
location = "india"

In [3]:
# Parameters
location = "nigeria"

In [4]:
def aggregate_by_scenario(df):
    return df.groupby(["scenario", "input_draw", "wealth_quintile"]).value.sum().groupby(["scenario", "wealth_quintile"]).mean()

In [5]:
pregnancy_ylls = (
    pd.read_parquet(f"0100_rescale_results/pregnancy_results/{location}/ylls.parquet")
)
pregnancy_ylls

,measure,entity_type,entity,sub_entity,age_group,anemia_status_at_birth,wealth_quintile,scenario,random_seed,input_draw,value
0,ylls,cause,maternal_disorders,maternal_disorders,10_to_14,invalid,lowest,baseline,1,0,0.0
1,ylls,cause,other_causes,other_causes,10_to_14,invalid,lowest,baseline,1,0,0.0
2,ylls,cause,maternal_disorders,maternal_disorders,10_to_14,invalid,second,baseline,1,0,0.0
3,ylls,cause,other_causes,other_causes,10_to_14,invalid,second,baseline,1,0,0.0
4,ylls,cause,maternal_disorders,maternal_disorders,10_to_14,invalid,middle,baseline,1,0,0.0
...,...,...,...,...,...,...,...,...,...,...,...
35995,ylls,cause,other_causes,other_causes,95_plus,severe,middle,intervention,5,0,0.0
35996,ylls,cause,maternal_disorders,maternal_disorders,95_plus,severe,fourth,intervention,5,0,0.0
35997,ylls,cause,other_causes,other_causes,95_plus,severe,fourth,intervention,5,0,0.0
35998,ylls,cause,maternal_disorders,maternal_disorders,95_plus,severe,highest,intervention,5,0,0.0
35999,ylls,cause,other_causes,other_causes,95_plus,severe,highest,intervention,5,0,0.0

In [6]:
pregnancy_ylls_by_scenario = aggregate_by_scenario(pregnancy_ylls)
pregnancy_ylls_by_scenario

scenario      wealth_quintile
baseline      fourth             156680.374672
              highest            112907.805479
              lowest             282639.097137
              middle             161790.398718
              second             258072.370261
intervention  fourth             156680.374672
              highest            112907.805479
              lowest             281906.264340
              middle             160836.987454
              second             258072.370261
Name: value, dtype: float64

In [7]:
pregnancy_ylls_averted = pregnancy_ylls_by_scenario.loc["baseline"] - pregnancy_ylls_by_scenario.loc["intervention"]
pregnancy_ylls_averted

wealth_quintile
fourth     0.000000e+00
highest    1.455192e-11
lowest     7.328328e+02
middle     9.534113e+02
second     0.000000e+00
Name: value, dtype: float64

In [8]:
pregnancy_ylds = pd.read_parquet(f"0100_rescale_results/pregnancy_results/{location}/ylds.parquet")
pregnancy_ylds

,measure,entity_type,entity,sub_entity,age_group,anemia_status_at_birth,wealth_quintile,scenario,random_seed,input_draw,value
0,ylds,cause,all_causes,all_causes,10_to_14,invalid,lowest,baseline,1,0,6.961176
1,ylds,cause,pregnancy,pregnant,10_to_14,invalid,lowest,baseline,1,0,0.000000
2,ylds,cause,pregnancy,parturition,10_to_14,invalid,lowest,baseline,1,0,0.000000
3,ylds,cause,pregnancy,postpartum,10_to_14,invalid,lowest,baseline,1,0,0.000000
4,ylds,cause,maternal_disorders,maternal_disorders,10_to_14,invalid,lowest,baseline,1,0,0.000000
...,...,...,...,...,...,...,...,...,...,...,...
125995,ylds,cause,pregnancy,parturition,95_plus,severe,highest,intervention,5,0,0.000000
125996,ylds,cause,pregnancy,postpartum,95_plus,severe,highest,intervention,5,0,0.000000
125997,ylds,cause,maternal_disorders,maternal_disorders,95_plus,severe,highest,intervention,5,0,0.000000
125998,ylds,cause,maternal_hemorrhage,maternal_hemorrhage,95_plus,severe,highest,intervention,5,0,0.000000
125999,ylds,cause,anemia,anemia,95_plus,severe,highest,intervention,5,0,0.000000

In [9]:
pregnancy_ylds_by_scenario = aggregate_by_scenario(pregnancy_ylds)
pregnancy_ylds_by_scenario

scenario      wealth_quintile
baseline      fourth             20896.286762
              highest            15411.361018
              lowest             36859.122291
              middle             30182.202113
              second             43222.287369
intervention  fourth             20851.638359
              highest            15410.120500
              lowest             35766.384761
              middle             29991.756858
              second             42370.716726
Name: value, dtype: float64

In [10]:
pregnancy_ylds_averted = pregnancy_ylds_by_scenario.loc["baseline"] - pregnancy_ylds_by_scenario.loc["intervention"]
pregnancy_ylds_averted

wealth_quintile
fourth       44.648403
highest       1.240518
lowest     1092.737530
middle      190.445255
second      851.570643
Name: value, dtype: float64

In [11]:
pregnancy_dalys_averted = pregnancy_ylls_averted + pregnancy_ylds_averted
pregnancy_dalys_averted

wealth_quintile
fourth       44.648403
highest       1.240518
lowest     1825.570328
middle     1143.856519
second      851.570643
Name: value, dtype: float64

In [12]:
assert len(pd.read_parquet(f"0100_rescale_results/child_results/{location}/ylds.parquet")) == 0

In [13]:
child_ylls = pd.read_parquet(f"0100_rescale_results/child_results/{location}/ylls.parquet").rename(columns={"maternal_scenario": "scenario"})
child_ylls

,measure,entity_type,entity,sub_entity,age_group,sex,wealth_quintile,child_scenario,scenario,random_seed,input_draw,value
0,ylls,cause,stillborn,stillborn,0_to_6_months,Female,lowest,baseline,baseline,4,0,0.000000
1,ylls,cause,stillborn,stillborn,0_to_6_months,Female,second,baseline,baseline,4,0,0.000000
2,ylls,cause,stillborn,stillborn,0_to_6_months,Female,middle,baseline,baseline,4,0,0.000000
3,ylls,cause,stillborn,stillborn,0_to_6_months,Female,fourth,baseline,baseline,4,0,0.000000
4,ylls,cause,stillborn,stillborn,0_to_6_months,Female,highest,baseline,baseline,4,0,0.000000
...,...,...,...,...,...,...,...,...,...,...,...,...
3195,ylls,cause,other_causes,other_causes,18_to_59_months,Male,lowest,baseline,intervention,8,0,513356.521123
3196,ylls,cause,other_causes,other_causes,18_to_59_months,Male,second,baseline,intervention,8,0,483407.801346
3197,ylls,cause,other_causes,other_causes,18_to_59_months,Male,middle,baseline,intervention,8,0,501089.343873
3198,ylls,cause,other_causes,other_causes,18_to_59_months,Male,fourth,baseline,intervention,8,0,432039.710916
3199,ylls,cause,other_causes,other_causes,18_to_59_months,Male,highest,baseline,intervention,8,0,370028.434888

In [14]:
child_ylls_by_scenario = aggregate_by_scenario(child_ylls)
child_ylls_by_scenario

scenario      wealth_quintile
baseline      fourth             5.499053e+07
              highest            4.836205e+07
              lowest             8.152427e+07
              middle             6.833477e+07
              second             8.137899e+07
intervention  fourth             5.484124e+07
              highest            4.822375e+07
              lowest             8.102177e+07
              middle             6.807897e+07
              second             8.085773e+07
Name: value, dtype: float64

In [15]:
child_ylls_averted = child_ylls_by_scenario.loc["baseline"] - child_ylls_by_scenario.loc["intervention"]
child_ylls_averted

wealth_quintile
fourth     149282.606081
highest    138293.090100
lowest     502492.297237
middle     255800.915742
second     521262.090430
Name: value, dtype: float64

In [16]:
f'{round(child_ylls_averted.sum()):,}'

'1,567,131'

In [17]:
child_days_averted = child_ylls_averted + 0

In [18]:
dalys_averted = pregnancy_dalys_averted + child_days_averted
dalys_averted

wealth_quintile
fourth     149327.254484
highest    138294.330619
lowest     504317.867565
middle     256944.772261
second     522113.661073
Name: value, dtype: float64

In [19]:
f'{round(dalys_averted.sum()):,}'

'1,570,998'