In [1]:
import pandas as pd

In [2]:
vehicle = pd.read_excel("./Data Extraction Sheet.xlsx", sheet_name="Vehicle Extraction")
vehicle

/mnt/share/homes/zmbc/src/vivarium_gates_lsff_by_wealth_quintile/.venv/lib/python3.11/site-packages/openpyxl/worksheet/_reader.py:329: UserWarning: Data Validation extension is not supported and will be removed
  warn(msg)

,Vehicle,Data need,Data point name,Units,Year,Data source,Value,CI,Notes
0,Rice,Iron fortification/consumption effect on hemog...,Mean difference,g/L,Unpublished,Dorbu et al. Nutritional anemia reductions due...,3.25,0.9-5.71,"""This comes from a slide deck that Jonathan se..."
1,Salt,Iron fortification/consumption effect on hemog...,Mean difference,g/L,2021,Can Double Fortification of Salt with Iron and...,4.40,2.3-6.4,https://www.ncbi.nlm.nih.gov/pmc/articles/PMC7...
2,Bouillon,Iron fortification/consumption effect on hemog...,Mean difference,g/L,2012,Effect of iron-fortified foods on hematologic ...,4.20,2.8-5.6,https://www.sciencedirect.com/science/article/...
3,Rice,Iron fortification/consumption effect on birth...,Mean difference,g/(mg/person-day),2013,"Anaemia, prenatal iron use, and risk of advers...",16.70,7.29 to 26.11,https://www.bmj.com/content/346/bmj.f3443; stu...
4,Bouillon,Iron fortification/consumption effect on birth...,Mean difference,g/(mg/person-day),2013,"Anaemia, prenatal iron use, and risk of advers...",16.70,7.29 to 26.11,https://www.bmj.com/content/346/bmj.f3443; stu...

In [3]:
vehicle["Data need"].unique()

array(['Iron fortification/consumption effect on hemoglobin',
       'Iron fortification/consumption effect on birthweight'],
      dtype=object)

In [4]:
hemoglobin_effects = vehicle[
    vehicle["Data need"] == "Iron fortification/consumption effect on hemoglobin"
].copy()
assert (hemoglobin_effects["Data point name"] == "Mean difference").all()
assert (hemoglobin_effects["Units"] == "g/L").all()
hemoglobin_effects = hemoglobin_effects[["Vehicle", "Value"]].rename(
    columns={"Vehicle": "vehicle_name", "Value": "value"}
)
hemoglobin_effects["vehicle_name"] = hemoglobin_effects.vehicle_name.str.lower()
hemoglobin_effects

  vehicle_name  value
0         rice   3.25
1         salt   4.40
2     bouillon   4.20

In [5]:
results_dir = (
    "../results"
)
hemoglobin_effects.to_csv(
    f"{results_dir}/iron/fortification_hemoglobin_effects.csv", index=False
)

In [6]:
birthweight_effects = vehicle[
    vehicle["Data need"] == "Iron fortification/consumption effect on birthweight"
].copy()
assert (birthweight_effects["Data point name"] == "Mean difference").all()
assert (birthweight_effects["Units"] == "g/(mg/person-day)").all()
birthweight_effects = birthweight_effects[["Vehicle", "Value"]].rename(
    columns={"Vehicle": "vehicle_name", "Value": "value"}
)
birthweight_effects["vehicle_name"] = birthweight_effects.vehicle_name.str.lower()
birthweight_effects

  vehicle_name  value
3         rice   16.7
4     bouillon   16.7

In [7]:
birthweight_effects.to_csv(
    f"{results_dir}/iron/fortification_birthweight_effects.csv", index=False
)