In [1]:
import pandas as pd
import vivarium_inputs
import vivarium.gbd_mapping as gbd_mapping
import pathlib
from lsff_utils import config_utils
from lsff_utils.results import expand_to_all_scenarios, aggregate_by_cause_and_scenario

In [2]:
location = "india"
vehicle = "rice"

In [3]:
# Parameters
location = "nigeria"
vehicle = "rice"

In [4]:
scenarios = list(
    config_utils.get_location_fortificant_vehicle_intervention_scenarios()
    .pipe(lambda df: df[(df.location == location) & (df.vehicle == vehicle)])
    .intervention_scenario.unique()
) + ["zero", "baseline"]
scenarios

['intervention', 'zero', 'baseline']

In [5]:
path = f"results/rescaled_pregnancy_results/{vehicle}/{location}/ylls.parquet"
if pathlib.Path(path).is_file():
    pregnancy_ylls = pd.read_parquet(path)
else:
    pregnancy_ylls = expand_to_all_scenarios(
        pd.read_parquet(
            f"results/rescaled_pregnancy_results/rice/india/ylls.parquet"
        ).assign(value=0),
        scenarios,
    )
pregnancy_ylls

,measure,entity_type,entity,sub_entity,age_group,anemia_status_at_birth,wealth_quintile,scenario,input_draw,random_seed,value
0,ylls,cause,other_causes,other_causes,10_to_14,invalid,1,baseline,0,141,0.0
1,ylls,cause,other_causes,other_causes,10_to_14,invalid,2,baseline,0,141,0.0
2,ylls,cause,other_causes,other_causes,10_to_14,invalid,3,baseline,0,141,0.0
3,ylls,cause,other_causes,other_causes,10_to_14,invalid,4,baseline,0,141,0.0
4,ylls,cause,other_causes,other_causes,10_to_14,invalid,5,baseline,0,141,0.0
...,...,...,...,...,...,...,...,...,...,...,...
539995,ylls,cause,maternal_disorders,maternal_disorders,95_plus,severe,1,zero,0,129,0.0
539996,ylls,cause,maternal_disorders,maternal_disorders,95_plus,severe,2,zero,0,129,0.0
539997,ylls,cause,maternal_disorders,maternal_disorders,95_plus,severe,3,zero,0,129,0.0
539998,ylls,cause,maternal_disorders,maternal_disorders,95_plus,severe,4,zero,0,129,0.0
539999,ylls,cause,maternal_disorders,maternal_disorders,95_plus,severe,5,zero,0,129,0.0

In [6]:
pregnancy_ylls.groupby("scenario").random_seed.nunique()

scenario
baseline        200
intervention    200
zero            200
Name: random_seed, dtype: int64

In [7]:
assert (pregnancy_ylls[pregnancy_ylls.value > 0].entity == "maternal_disorders").all()

In [8]:
pregnancy_ylls_by_scenario = aggregate_by_cause_and_scenario(pregnancy_ylls).pipe(
    lambda df: df[df.index.get_level_values("entity") == "maternal_disorders"]
)
pregnancy_ylls_by_scenario

scenario      entity              wealth_quintile
baseline      maternal_disorders  1                  521802.258047
                                  2                  521556.880782
                                  3                  350999.059500
                                  4                  306126.567588
                                  5                  214125.472505
intervention  maternal_disorders  1                  520030.298129
                                  2                  519505.948732
                                  3                  349185.834744
                                  4                  303926.758580
                                  5                  212749.045724
zero          maternal_disorders  1                  521802.258047
                                  2                  521556.880782
                                  3                  350999.059500
                                  4                  306126.567588
                                  5                  214125.472505
Name: value, dtype: float64

In [9]:
path = f"results/rescaled_pregnancy_results/{vehicle}/{location}/ylds.parquet"
if pathlib.Path(path).is_file():
    pregnancy_ylds = pd.read_parquet(path)
else:
    pregnancy_ylds = expand_to_all_scenarios(
        pd.read_parquet(
            f"results/rescaled_pregnancy_results/rice/india/ylds.parquet"
        ).assign(value=0),
        scenarios,
    )

pregnancy_ylds

,measure,entity_type,entity,sub_entity,age_group,anemia_status_at_birth,wealth_quintile,scenario,input_draw,random_seed,value
0,ylds,cause,pregnancy,pregnant,10_to_14,invalid,1,baseline,0,141,0.0
1,ylds,cause,pregnancy,parturition,10_to_14,invalid,1,baseline,0,141,0.0
2,ylds,cause,pregnancy,postpartum,10_to_14,invalid,1,baseline,0,141,0.0
3,ylds,cause,maternal_disorders,maternal_disorders,10_to_14,invalid,1,baseline,0,141,0.0
4,ylds,cause,maternal_hemorrhage,maternal_hemorrhage,10_to_14,invalid,1,baseline,0,141,0.0
...,...,...,...,...,...,...,...,...,...,...,...
1889995,ylds,cause,pregnancy,postpartum,95_plus,severe,5,zero,0,129,0.0
1889996,ylds,cause,maternal_disorders,maternal_disorders,95_plus,severe,5,zero,0,129,0.0
1889997,ylds,cause,maternal_hemorrhage,maternal_hemorrhage,95_plus,severe,5,zero,0,129,0.0
1889998,ylds,cause,all_causes,all_causes,95_plus,severe,5,zero,0,129,0.0
1889999,ylds,cause,anemia,anemia,95_plus,severe,5,zero,0,129,0.0

In [10]:
# Pregnancy has no disability, and maternal hemorrhage disability is counted in maternal_disorders
assert (
    pregnancy_ylds[
        pregnancy_ylds.entity.isin(["pregnancy", "maternal_hemorrhage"])
    ].value
    == 0
).all()

In [11]:
pregnancy_ylds_by_scenario = aggregate_by_cause_and_scenario(pregnancy_ylds).pipe(
    lambda df: df[
        ~df.index.get_level_values("entity").isin(["pregnancy", "maternal_hemorrhage"])
    ]
)
pregnancy_ylds_by_scenario

scenario      entity              wealth_quintile
baseline      anemia              1                  48391.359889
                                  2                  56771.960899
                                  3                  39968.120155
                                  4                  28851.999957
                                  5                  21313.304283
              maternal_disorders  1                  28196.304199
                                  2                  25188.698788
                                  3                  17676.470723
                                  4                  16208.682639
                                  5                  12541.402770
intervention  anemia              1                  47716.826145
                                  2                  55694.770185
                                  3                  38936.884061
                                  4                  27983.557848
                                  5                  20539.852895
              maternal_disorders  1                  28118.195298
                                  2                  25076.201340
                                  3                  17562.412778
                                  4                  16105.458034
                                  5                  12443.198121
zero          anemia              1                  48391.359889
                                  2                  56771.960899
                                  3                  39968.120155
                                  4                  28851.999957
                                  5                  21313.304283
              maternal_disorders  1                  28196.304199
                                  2                  25188.698788
                                  3                  17676.470723
                                  4                  16208.682639
                                  5                  12541.402770
Name: value, dtype: float64

In [12]:
pregnancy_dalys_by_scenario = pregnancy_ylls_by_scenario.add(
    pregnancy_ylds_by_scenario, fill_value=0
)
pregnancy_dalys_by_scenario

scenario      entity              wealth_quintile
baseline      anemia              1                   48391.359889
                                  2                   56771.960899
                                  3                   39968.120155
                                  4                   28851.999957
                                  5                   21313.304283
              maternal_disorders  1                  549998.562245
                                  2                  546745.579570
                                  3                  368675.530223
                                  4                  322335.250227
                                  5                  226666.875275
intervention  anemia              1                   47716.826145
                                  2                   55694.770185
                                  3                   38936.884061
                                  4                   27983.557848
                                  5                   20539.852895
              maternal_disorders  1                  548148.493427
                                  2                  544582.150072
                                  3                  366748.247523
                                  4                  320032.216614
                                  5                  225192.243845
zero          anemia              1                   48391.359889
                                  2                   56771.960899
                                  3                   39968.120155
                                  4                   28851.999957
                                  5                   21313.304283
              maternal_disorders  1                  549998.562245
                                  2                  546745.579570
                                  3                  368675.530223
                                  4                  322335.250227
                                  5                  226666.875275
Name: value, dtype: float64

In [13]:
ylds_path = f"results/rescaled_child_results/{vehicle}/{location}/ylds.parquet"
if pathlib.Path(ylds_path).is_file():
    assert (pd.read_parquet(ylds_path)['value'] == 0).all()

In [14]:
path = f"results/rescaled_child_results/{vehicle}/{location}/ylls.parquet"

# NOTE: The child_scenario column currently contains only 'baseline'
# because we didn't have any interventions in the child simulation. If
# we add a child intervention that creates another scenario in this
# column, then results from different child scenarios would get added
# together in the call to aggregate_by_cause_and_scenario below, so we'd
# need to change the processing code in that case.
def assert_unique_child_scenario(df):
    assert set(df.child_scenario.unique()) == {'baseline'}
    return df

if pathlib.Path(path).is_file():
    neonatal_ylls = (
        pd.read_parquet(path)
        .pipe(assert_unique_child_scenario)
        .rename(columns={"maternal_scenario": "scenario"})
    )
else:
    # NOTE: This else branch is for processing the Ethiopia results,
    # where no Vivarium sims were run, so the corresponding DALYs should
    # just be 0
    neonatal_ylls = expand_to_all_scenarios(
        pd.read_parquet(f"results/rescaled_child_results/rice/india/ylls.parquet")
        .assign(value=0)
        .rename(columns={"maternal_scenario": "scenario"}),
        scenarios,
    )

neonatal_ylls

,measure,entity_type,entity,sub_entity,age_group,sex,wealth_quintile,child_scenario,scenario,input_draw,random_seed,value
0,ylls,cause,other_causes,other_causes,0_to_5_months,Female,1,baseline,baseline,0,81,20209.792653
1,ylls,cause,other_causes,other_causes,0_to_5_months,Female,2,baseline,baseline,0,81,20063.061953
2,ylls,cause,other_causes,other_causes,0_to_5_months,Female,3,baseline,baseline,0,81,16985.810845
3,ylls,cause,other_causes,other_causes,0_to_5_months,Female,4,baseline,baseline,0,81,12740.042209
4,ylls,cause,other_causes,other_causes,0_to_5_months,Female,5,baseline,baseline,0,81,10539.718476
...,...,...,...,...,...,...,...,...,...,...,...,...
23995,ylls,cause,other_causes,other_causes,18_to_59_months,Male,1,baseline,intervention,0,71,13444.183556
23996,ylls,cause,other_causes,other_causes,18_to_59_months,Male,2,baseline,intervention,0,71,15298.498950
23997,ylls,cause,other_causes,other_causes,18_to_59_months,Male,3,baseline,intervention,0,71,12449.381005
23998,ylls,cause,other_causes,other_causes,18_to_59_months,Male,4,baseline,intervention,0,71,9934.268746
23999,ylls,cause,other_causes,other_causes,18_to_59_months,Male,5,baseline,intervention,0,71,8790.407288

In [15]:
neonatal_ylls_by_scenario = aggregate_by_cause_and_scenario(neonatal_ylls)
assert (
    neonatal_ylls_by_scenario[
        neonatal_ylls_by_scenario.index.get_level_values("entity") != "other_causes"
    ]
    == 0
).all()
neonatal_ylls_by_scenario = neonatal_ylls_by_scenario[
    neonatal_ylls_by_scenario.index.get_level_values("entity") == "other_causes"
]
neonatal_ylls_by_scenario = (
    neonatal_ylls_by_scenario.reset_index()
    .assign(entity="lbwsg")
    .set_index(neonatal_ylls_by_scenario.index.names)
    .value
)
neonatal_ylls_by_scenario

scenario      entity  wealth_quintile
baseline      lbwsg   1                  1.701180e+07
                      2                  1.726212e+07
                      3                  1.435806e+07
                      4                  1.151587e+07
                      5                  1.005105e+07
intervention  lbwsg   1                  1.701019e+07
                      2                  1.725904e+07
                      3                  1.435586e+07
                      4                  1.151323e+07
                      5                  1.004826e+07
zero          lbwsg   1                  1.701180e+07
                      2                  1.726212e+07
                      3                  1.435806e+07
                      4                  1.151587e+07
                      5                  1.005105e+07
Name: value, dtype: float64

In [16]:
path = f"../0400_non_pregnant_anemia_model/results/{vehicle}/{location}/ylds.parquet"
if pathlib.Path(path).is_file():
    non_pregnancy_anemia_ylds = pd.read_parquet(path)
else:
    non_pregnancy_anemia_ylds = expand_to_all_scenarios(
        pd.read_parquet(
            f"../0400_non_pregnant_anemia_model/results/rice/india/ylds.parquet"
        ).assign(value=0),
        scenarios,
    )

non_pregnancy_anemia_ylds

        sex  age_start     age_end  wealth_quintile       value      scenario
0    Female        0.0    0.019178                1  800.283562          zero
1    Female        0.0    0.019178                2  706.841012          zero
2    Female        0.0    0.019178                3  572.445535          zero
3    Female        0.0    0.019178                4  465.318737          zero
4    Female        0.0    0.019178                5  335.008818          zero
..      ...        ...         ...              ...         ...           ...
745    Male       95.0  125.000000                1  286.403297  intervention
746    Male       95.0  125.000000                2  238.717041  intervention
747    Male       95.0  125.000000                3  242.112364  intervention
748    Male       95.0  125.000000                4  254.669907  intervention
749    Male       95.0  125.000000                5  254.357830  intervention

[750 rows x 6 columns]

In [17]:
# For comparison with previous round of results, we also look at
# WRA and U5
wra_non_pregnancy_anemia_ylds_by_scenario = aggregate_by_cause_and_scenario(
    non_pregnancy_anemia_ylds[
        (non_pregnancy_anemia_ylds.sex == "Female")
        & (non_pregnancy_anemia_ylds.age_start >= 10)
        & (non_pregnancy_anemia_ylds.age_end <= 55)
    ].assign(entity="anemia", input_draw="draw_0")
)
wra_non_pregnancy_anemia_ylds_by_scenario

scenario      entity  wealth_quintile
baseline      anemia  1                  310752.033559
                      2                  284413.095389
                      3                  275295.458783
                      4                  277105.985516
                      5                  229264.217677
intervention  anemia  1                  307009.898562
                      2                  279583.007139
                      3                  269547.786028
                      4                  270183.538419
                      5                  222709.263510
zero          anemia  1                  310752.033559
                      2                  284413.095389
                      3                  275295.458783
                      4                  277105.985516
                      5                  229264.217677
Name: value, dtype: float64

In [18]:
scenarios[1]

'zero'

In [19]:
(
    wra_non_pregnancy_anemia_ylds_by_scenario.loc["baseline"].sum()
    + pregnancy_ylds_by_scenario.loc[("baseline", "anemia")].sum()
) - (
    wra_non_pregnancy_anemia_ylds_by_scenario.loc[scenarios[1]].sum()
    + pregnancy_ylds_by_scenario.loc[(scenarios[1], "anemia")].sum()
)

0.0

In [20]:
u5_anemia_ylds_by_scenario = aggregate_by_cause_and_scenario(
    non_pregnancy_anemia_ylds[(non_pregnancy_anemia_ylds.age_end <= 5)].assign(
        entity="anemia", input_draw="draw_0"
    )
)
u5_anemia_ylds_by_scenario

scenario      entity  wealth_quintile
baseline      anemia  1                  310419.898912
                      2                  266393.739987
                      3                  197235.529551
                      4                  166337.049788
                      5                   97850.259205
intervention  anemia  1                  307132.068710
                      2                  262284.940307
                      3                  193120.533837
                      4                  162079.969485
                      5                   94579.366689
zero          anemia  1                  310419.898912
                      2                  266393.739987
                      3                  197235.529551
                      4                  166337.049788
                      5                   97850.259205
Name: value, dtype: float64

In [21]:
(
    u5_anemia_ylds_by_scenario.loc["baseline"].sum()
    - u5_anemia_ylds_by_scenario.loc[scenarios[1]].sum()
)

0.0

In [22]:
non_pregnancy_anemia_ylds_by_scenario = aggregate_by_cause_and_scenario(
    non_pregnancy_anemia_ylds.assign(entity="anemia", input_draw="draw_0")
)
non_pregnancy_anemia_ylds_by_scenario

scenario      entity  wealth_quintile
baseline      anemia  1                  1.059664e+06
                      2                  8.923464e+05
                      3                  7.728718e+05
                      4                  7.150491e+05
                      5                  5.134143e+05
intervention  anemia  1                  1.047370e+06
                      2                  8.775892e+05
                      3                  7.566684e+05
                      4                  6.970287e+05
                      5                  4.983022e+05
zero          anemia  1                  1.059664e+06
                      2                  8.923464e+05
                      3                  7.728718e+05
                      4                  7.150491e+05
                      5                  5.134143e+05
Name: value, dtype: float64

In [23]:
path = f"../0500_neural_tube_defects_model/results/{location}/{vehicle}/ylls_by_scenario.csv"
if pathlib.Path(path).is_file():
    neural_tube_defect_ylls_by_scenario = pd.read_csv(path)
else:
    neural_tube_defect_ylls_by_scenario = expand_to_all_scenarios(
        pd.read_csv(
            f"../0500_neural_tube_defects_model/results/india/rice/intervention/ylls_by_scenario.csv"
        ).assign(value=0),
        scenarios,
    )

neural_tube_defect_ylls_by_scenario = neural_tube_defect_ylls_by_scenario.set_index(
    ["scenario", "entity", "wealth_quintile"]
).value
neural_tube_defect_ylls_by_scenario

scenario      entity  wealth_quintile
zero          ntd     1                  414148.385733
                      2                  423492.501283
                      3                  383377.246596
                      4                  339825.075845
                      5                  298474.679448
baseline      ntd     1                  414148.385733
                      2                  423492.501283
                      3                  383377.246596
                      4                  339825.075845
                      5                  298474.679448
intervention  ntd     1                  396815.202062
                      2                  389996.372062
                      3                  341467.391332
                      4                  290669.193264
                      5                  250632.466206
Name: value, dtype: float64

In [24]:
dalys_by_scenario = (
    pregnancy_dalys_by_scenario.add(neonatal_ylls_by_scenario, fill_value=0)
    .add(non_pregnancy_anemia_ylds_by_scenario, fill_value=0)
    .add(neural_tube_defect_ylls_by_scenario, fill_value=0)
)
dalys_by_scenario

scenario      entity              wealth_quintile
baseline      anemia              1                  1.108056e+06
                                  2                  9.491183e+05
                                  3                  8.128399e+05
                                  4                  7.439011e+05
                                  5                  5.347276e+05
              lbwsg               1                  1.701180e+07
                                  2                  1.726212e+07
                                  3                  1.435806e+07
                                  4                  1.151587e+07
                                  5                  1.005105e+07
              maternal_disorders  1                  5.499986e+05
                                  2                  5.467456e+05
                                  3                  3.686755e+05
                                  4                  3.223353e+05
                                  5                  2.266669e+05
              ntd                 1                  4.141484e+05
                                  2                  4.234925e+05
                                  3                  3.833772e+05
                                  4                  3.398251e+05
                                  5                  2.984747e+05
intervention  anemia              1                  1.095087e+06
                                  2                  9.332839e+05
                                  3                  7.956053e+05
                                  4                  7.250122e+05
                                  5                  5.188421e+05
              lbwsg               1                  1.701019e+07
                                  2                  1.725904e+07
                                  3                  1.435586e+07
                                  4                  1.151323e+07
                                  5                  1.004826e+07
              maternal_disorders  1                  5.481485e+05
                                  2                  5.445822e+05
                                  3                  3.667482e+05
                                  4                  3.200322e+05
                                  5                  2.251922e+05
              ntd                 1                  3.968152e+05
                                  2                  3.899964e+05
                                  3                  3.414674e+05
                                  4                  2.906692e+05
                                  5                  2.506325e+05
zero          anemia              1                  1.108056e+06
                                  2                  9.491183e+05
                                  3                  8.128399e+05
                                  4                  7.439011e+05
                                  5                  5.347276e+05
              lbwsg               1                  1.701180e+07
                                  2                  1.726212e+07
                                  3                  1.435806e+07
                                  4                  1.151587e+07
                                  5                  1.005105e+07
              maternal_disorders  1                  5.499986e+05
                                  2                  5.467456e+05
                                  3                  3.686755e+05
                                  4                  3.223353e+05
                                  5                  2.266669e+05
              ntd                 1                  4.141484e+05
                                  2                  4.234925e+05
                                  3                  3.833772e+05
                                  4                  3.398251e+05
                                  5                  2.984747e+05
Name: value, dtype: float64

In [25]:
import pathlib

In [26]:
path = f"./results/{location}/{vehicle}/dalys_by_scenario.csv"
pathlib.Path(path).parent.mkdir(exist_ok=True, parents=True)
dalys_by_scenario.to_csv(path)