In [1]:
import pandas as pd
import vivarium_inputs
import vivarium.gbd_mapping as gbd_mapping
import pathlib
from lsff_utils import config_utils
from lsff_utils.results import expand_to_all_scenarios, aggregate_by_cause_and_scenario

In [2]:
location = "india"
vehicle = "rice"

In [3]:
# Parameters
location = "nigeria"
vehicle = "bouillon"

In [4]:
scenarios = list(
    config_utils.get_location_fortificant_vehicle_intervention_scenarios()
    .pipe(lambda df: df[(df.location == location) & (df.vehicle == vehicle)])
    .intervention_scenario.unique()
) + ["zero", "baseline"]
scenarios

['intervention', 'zero', 'baseline']

In [5]:
path = f"results/rescaled_pregnancy_results/{vehicle}/{location}/ylls.parquet"
if pathlib.Path(path).is_file():
    pregnancy_ylls = pd.read_parquet(path)
else:
    pregnancy_ylls = expand_to_all_scenarios(
        pd.read_parquet(
            f"results/rescaled_pregnancy_results/rice/india/ylls.parquet"
        ).assign(value=0),
        scenarios,
    )
pregnancy_ylls

,measure,entity_type,entity,sub_entity,age_group,anemia_status_at_birth,wealth_quintile,scenario,input_draw,random_seed,value
0,ylls,cause,other_causes,other_causes,10_to_14,invalid,1,baseline,0,2,0.0
1,ylls,cause,other_causes,other_causes,10_to_14,invalid,2,baseline,0,2,0.0
2,ylls,cause,other_causes,other_causes,10_to_14,invalid,3,baseline,0,2,0.0
3,ylls,cause,other_causes,other_causes,10_to_14,invalid,4,baseline,0,2,0.0
4,ylls,cause,other_causes,other_causes,10_to_14,invalid,5,baseline,0,2,0.0
...,...,...,...,...,...,...,...,...,...,...,...
26995,ylls,cause,maternal_disorders,maternal_disorders,95_plus,severe,1,baseline,0,9,0.0
26996,ylls,cause,maternal_disorders,maternal_disorders,95_plus,severe,2,baseline,0,9,0.0
26997,ylls,cause,maternal_disorders,maternal_disorders,95_plus,severe,3,baseline,0,9,0.0
26998,ylls,cause,maternal_disorders,maternal_disorders,95_plus,severe,4,baseline,0,9,0.0
26999,ylls,cause,maternal_disorders,maternal_disorders,95_plus,severe,5,baseline,0,9,0.0

In [6]:
pregnancy_ylls.groupby("scenario").random_seed.nunique()

scenario
baseline        10
intervention    10
zero            10
Name: random_seed, dtype: int64

In [7]:
assert (pregnancy_ylls[pregnancy_ylls.value > 0].entity == "maternal_disorders").all()

In [8]:
pregnancy_ylls_by_scenario = aggregate_by_cause_and_scenario(pregnancy_ylls).pipe(
    lambda df: df[df.index.get_level_values("entity") == "maternal_disorders"]
)
pregnancy_ylls_by_scenario

scenario      entity              wealth_quintile
baseline      maternal_disorders  1                  511450.666820
                                  2                  566785.485785
                                  3                  344594.797818
                                  4                  288052.056367
                                  5                  239022.460134
intervention  maternal_disorders  1                  482062.614256
                                  2                  541483.799645
                                  3                  334168.369908
                                  4                  278088.522752
                                  5                  225562.916642
zero          maternal_disorders  1                  511450.666820
                                  2                  566785.485785
                                  3                  344594.797818
                                  4                  288052.056367
                                  5                  239022.460134
Name: value, dtype: float64

In [9]:
path = f"results/rescaled_pregnancy_results/{vehicle}/{location}/ylds.parquet"
if pathlib.Path(path).is_file():
    pregnancy_ylds = pd.read_parquet(path)
else:
    pregnancy_ylds = expand_to_all_scenarios(
        pd.read_parquet(
            f"results/rescaled_pregnancy_results/rice/india/ylds.parquet"
        ).assign(value=0),
        scenarios,
    )

pregnancy_ylds

,measure,entity_type,entity,sub_entity,age_group,anemia_status_at_birth,wealth_quintile,scenario,input_draw,random_seed,value
0,ylds,cause,pregnancy,pregnant,10_to_14,invalid,1,baseline,0,2,0.0
1,ylds,cause,pregnancy,parturition,10_to_14,invalid,1,baseline,0,2,0.0
2,ylds,cause,pregnancy,postpartum,10_to_14,invalid,1,baseline,0,2,0.0
3,ylds,cause,maternal_disorders,maternal_disorders,10_to_14,invalid,1,baseline,0,2,0.0
4,ylds,cause,maternal_hemorrhage,maternal_hemorrhage,10_to_14,invalid,1,baseline,0,2,0.0
...,...,...,...,...,...,...,...,...,...,...,...
94495,ylds,cause,pregnancy,postpartum,95_plus,severe,5,baseline,0,9,0.0
94496,ylds,cause,maternal_disorders,maternal_disorders,95_plus,severe,5,baseline,0,9,0.0
94497,ylds,cause,maternal_hemorrhage,maternal_hemorrhage,95_plus,severe,5,baseline,0,9,0.0
94498,ylds,cause,all_causes,all_causes,95_plus,severe,5,baseline,0,9,0.0
94499,ylds,cause,anemia,anemia,95_plus,severe,5,baseline,0,9,0.0

In [10]:
# Pregnancy has no disability, and maternal hemorrhage disability is counted in maternal_disorders
assert (
    pregnancy_ylds[
        pregnancy_ylds.entity.isin(["pregnancy", "maternal_hemorrhage"])
    ].value
    == 0
).all()

In [11]:
pregnancy_ylds_by_scenario = aggregate_by_cause_and_scenario(pregnancy_ylds).pipe(
    lambda df: df[
        ~df.index.get_level_values("entity").isin(["pregnancy", "maternal_hemorrhage"])
    ]
)
pregnancy_ylds_by_scenario

scenario      entity              wealth_quintile
baseline      anemia              1                  48529.021788
                                  2                  56609.391322
                                  3                  39930.494636
                                  4                  28802.305815
                                  5                  21249.989928
              maternal_disorders  1                    104.522318
                                  2                     92.815370
                                  3                     65.833547
                                  4                     60.282997
                                  5                     46.318303
intervention  anemia              1                  39567.984830
                                  2                  46548.831365
                                  3                  32294.244258
                                  4                  23345.857457
                                  5                  16638.798157
              maternal_disorders  1                    100.579954
                                  2                     88.684438
                                  3                     62.589174
                                  4                     57.799340
                                  5                     44.151727
zero          anemia              1                  48529.021788
                                  2                  56609.391322
                                  3                  39930.494636
                                  4                  28802.305815
                                  5                  21249.989928
              maternal_disorders  1                    104.522318
                                  2                     92.815370
                                  3                     65.833547
                                  4                     60.282997
                                  5                     46.318303
Name: value, dtype: float64

In [12]:
pregnancy_dalys_by_scenario = pregnancy_ylls_by_scenario.add(
    pregnancy_ylds_by_scenario, fill_value=0
)
pregnancy_dalys_by_scenario

scenario      entity              wealth_quintile
baseline      anemia              1                   48529.021788
                                  2                   56609.391322
                                  3                   39930.494636
                                  4                   28802.305815
                                  5                   21249.989928
              maternal_disorders  1                  511555.189139
                                  2                  566878.301156
                                  3                  344660.631365
                                  4                  288112.339364
                                  5                  239068.778437
intervention  anemia              1                   39567.984830
                                  2                   46548.831365
                                  3                   32294.244258
                                  4                   23345.857457
                                  5                   16638.798157
              maternal_disorders  1                  482163.194211
                                  2                  541572.484083
                                  3                  334230.959082
                                  4                  278146.322092
                                  5                  225607.068370
zero          anemia              1                   48529.021788
                                  2                   56609.391322
                                  3                   39930.494636
                                  4                   28802.305815
                                  5                   21249.989928
              maternal_disorders  1                  511555.189139
                                  2                  566878.301156
                                  3                  344660.631365
                                  4                  288112.339364
                                  5                  239068.778437
Name: value, dtype: float64

In [13]:
ylds_path = f"results/rescaled_child_results/{vehicle}/{location}/ylds.parquet"
if pathlib.Path(ylds_path).is_file():
    assert (pd.read_parquet(ylds_path)['value'] == 0).all()

In [14]:
path = f"results/rescaled_child_results/{vehicle}/{location}/ylls.parquet"

# NOTE: The child_scenario column currently contains only 'baseline'
# because we didn't have any interventions in the child simulation. If
# we add a child intervention that creates another scenario in this
# column, then results from different child scenarios would get added
# together in the call to aggregate_by_cause_and_scenario below, so we'd
# need to change the processing code in that case.
def assert_unique_child_scenario(df):
    assert set(df.child_scenario.unique()) == {'baseline'}
    return df

if pathlib.Path(path).is_file():
    neonatal_ylls = (
        pd.read_parquet(path)
        .pipe(assert_unique_child_scenario)
        .rename(columns={"maternal_scenario": "scenario"})
    )
else:
    # NOTE: This else branch is for processing the Ethiopia results,
    # where no Vivarium sims were run, so the corresponding DALYs should
    # just be 0
    neonatal_ylls = expand_to_all_scenarios(
        pd.read_parquet(f"results/rescaled_child_results/rice/india/ylls.parquet")
        .assign(value=0)
        .rename(columns={"maternal_scenario": "scenario"}),
        scenarios,
    )

neonatal_ylls

,measure,entity_type,entity,sub_entity,age_group,sex,wealth_quintile,child_scenario,scenario,input_draw,random_seed,value
0,ylls,cause,other_causes,other_causes,0_to_5_months,Female,1,baseline,intervention,0,2,374784.059616
1,ylls,cause,other_causes,other_causes,0_to_5_months,Female,2,baseline,intervention,0,2,354317.173473
2,ylls,cause,other_causes,other_causes,0_to_5_months,Female,3,baseline,intervention,0,2,336675.332140
3,ylls,cause,other_causes,other_causes,0_to_5_months,Female,4,baseline,intervention,0,2,193299.016327
4,ylls,cause,other_causes,other_causes,0_to_5_months,Female,5,baseline,intervention,0,2,207856.029543
...,...,...,...,...,...,...,...,...,...,...,...,...
1195,ylls,cause,other_causes,other_causes,18_to_59_months,Male,1,baseline,intervention,0,6,325553.043218
1196,ylls,cause,other_causes,other_causes,18_to_59_months,Male,2,baseline,intervention,0,6,277453.727317
1197,ylls,cause,other_causes,other_causes,18_to_59_months,Male,3,baseline,intervention,0,6,251388.155772
1198,ylls,cause,other_causes,other_causes,18_to_59_months,Male,4,baseline,intervention,0,6,235019.923571
1199,ylls,cause,other_causes,other_causes,18_to_59_months,Male,5,baseline,intervention,0,6,121841.100326

In [15]:
neonatal_ylls_by_scenario = aggregate_by_cause_and_scenario(neonatal_ylls)
assert (
    neonatal_ylls_by_scenario[
        neonatal_ylls_by_scenario.index.get_level_values("entity") != "other_causes"
    ]
    == 0
).all()
neonatal_ylls_by_scenario = neonatal_ylls_by_scenario[
    neonatal_ylls_by_scenario.index.get_level_values("entity") == "other_causes"
]
neonatal_ylls_by_scenario = (
    neonatal_ylls_by_scenario.reset_index()
    .assign(entity="lbwsg")
    .set_index(neonatal_ylls_by_scenario.index.names)
    .value
)
neonatal_ylls_by_scenario

scenario      entity  wealth_quintile
baseline      lbwsg   1                  1.689969e+07
                      2                  1.695210e+07
                      3                  1.391306e+07
                      4                  1.148816e+07
                      5                  9.796241e+06
intervention  lbwsg   1                  1.678516e+07
                      2                  1.687010e+07
                      3                  1.384860e+07
                      4                  1.146179e+07
                      5                  9.772947e+06
zero          lbwsg   1                  1.689969e+07
                      2                  1.695210e+07
                      3                  1.391306e+07
                      4                  1.148816e+07
                      5                  9.796241e+06
Name: value, dtype: float64

In [16]:
path = f"../0400_non_pregnant_anemia_model/results/{vehicle}/{location}/ylds.parquet"
if pathlib.Path(path).is_file():
    non_pregnancy_anemia_ylds = pd.read_parquet(path)
else:
    non_pregnancy_anemia_ylds = expand_to_all_scenarios(
        pd.read_parquet(
            f"../0400_non_pregnant_anemia_model/results/rice/india/ylds.parquet"
        ).assign(value=0),
        scenarios,
    )

non_pregnancy_anemia_ylds

        sex  age_start     age_end  wealth_quintile       value      scenario
0    Female        0.0    0.019178                1  800.283562          zero
1    Female        0.0    0.019178                2  706.841012          zero
2    Female        0.0    0.019178                3  572.445535          zero
3    Female        0.0    0.019178                4  465.318737          zero
4    Female        0.0    0.019178                5  335.008818          zero
..      ...        ...         ...              ...         ...           ...
745    Male       95.0  125.000000                1  272.823452  intervention
746    Male       95.0  125.000000                2  226.607458  intervention
747    Male       95.0  125.000000                3  230.091144  intervention
748    Male       95.0  125.000000                4  241.675951  intervention
749    Male       95.0  125.000000                5  240.304664  intervention

[750 rows x 6 columns]

In [17]:
# For comparison with previous round of results, we also look at
# WRA and U5
wra_non_pregnancy_anemia_ylds_by_scenario = aggregate_by_cause_and_scenario(
    non_pregnancy_anemia_ylds[
        (non_pregnancy_anemia_ylds.sex == "Female")
        & (non_pregnancy_anemia_ylds.age_start >= 10)
        & (non_pregnancy_anemia_ylds.age_end <= 55)
    ].assign(entity="anemia", input_draw="draw_0")
)
wra_non_pregnancy_anemia_ylds_by_scenario

scenario      entity  wealth_quintile
baseline      anemia  1                  310752.033559
                      2                  284413.095389
                      3                  275295.458783
                      4                  277105.985516
                      5                  229264.217677
intervention  anemia  1                  267070.101059
                      2                  240898.498872
                      3                  232270.996032
                      4                  232377.801542
                      5                  189956.840050
zero          anemia  1                  310752.033559
                      2                  284413.095389
                      3                  275295.458783
                      4                  277105.985516
                      5                  229264.217677
Name: value, dtype: float64

In [18]:
scenarios[1]

'zero'

In [19]:
(
    wra_non_pregnancy_anemia_ylds_by_scenario.loc["baseline"].sum()
    + pregnancy_ylds_by_scenario.loc[("baseline", "anemia")].sum()
) - (
    wra_non_pregnancy_anemia_ylds_by_scenario.loc[scenarios[1]].sum()
    + pregnancy_ylds_by_scenario.loc[(scenarios[1], "anemia")].sum()
)

0.0

In [20]:
u5_anemia_ylds_by_scenario = aggregate_by_cause_and_scenario(
    non_pregnancy_anemia_ylds[(non_pregnancy_anemia_ylds.age_end <= 5)].assign(
        entity="anemia", input_draw="draw_0"
    )
)
u5_anemia_ylds_by_scenario

scenario      entity  wealth_quintile
baseline      anemia  1                  310419.898912
                      2                  266393.739987
                      3                  197235.529551
                      4                  166337.049788
                      5                   97850.259205
intervention  anemia  1                  271687.383368
                      2                  229052.463414
                      3                  166269.522369
                      4                  138700.275235
                      5                   78256.954057
zero          anemia  1                  310419.898912
                      2                  266393.739987
                      3                  197235.529551
                      4                  166337.049788
                      5                   97850.259205
Name: value, dtype: float64

In [21]:
(
    u5_anemia_ylds_by_scenario.loc["baseline"].sum()
    - u5_anemia_ylds_by_scenario.loc[scenarios[1]].sum()
)

0.0

In [22]:
non_pregnancy_anemia_ylds_by_scenario = aggregate_by_cause_and_scenario(
    non_pregnancy_anemia_ylds.assign(entity="anemia", input_draw="draw_0")
)
non_pregnancy_anemia_ylds_by_scenario

scenario      entity  wealth_quintile
baseline      anemia  1                  1.059664e+06
                      2                  8.923464e+05
                      3                  7.728718e+05
                      4                  7.150491e+05
                      5                  5.134143e+05
intervention  anemia  1                  9.159634e+05
                      2                  7.593257e+05
                      3                  6.517138e+05
                      4                  5.987840e+05
                      5                  4.230518e+05
zero          anemia  1                  1.059664e+06
                      2                  8.923464e+05
                      3                  7.728718e+05
                      4                  7.150491e+05
                      5                  5.134143e+05
Name: value, dtype: float64

In [23]:
path = f"../0500_neural_tube_defects_model/results/{location}/{vehicle}/ylls_by_scenario.csv"
if pathlib.Path(path).is_file():
    neural_tube_defect_ylls_by_scenario = pd.read_csv(path)
else:
    neural_tube_defect_ylls_by_scenario = expand_to_all_scenarios(
        pd.read_csv(
            f"../0500_neural_tube_defects_model/results/india/rice/intervention/ylls_by_scenario.csv"
        ).assign(value=0),
        scenarios,
    )

neural_tube_defect_ylls_by_scenario = neural_tube_defect_ylls_by_scenario.set_index(
    ["scenario", "entity", "wealth_quintile"]
).value
neural_tube_defect_ylls_by_scenario

scenario      entity  wealth_quintile
zero          ntd     1                  414148.385733
                      2                  423492.501283
                      3                  383377.246596
                      4                  339825.075845
                      5                  298474.679448
baseline      ntd     1                  414148.385733
                      2                  423492.501283
                      3                  383377.246596
                      4                  339825.075845
                      5                  298474.679448
intervention  ntd     1                  145389.486727
                      2                  158295.641486
                      3                  175691.140222
                      4                  175860.026689
                      5                  162222.428831
Name: value, dtype: float64

In [24]:
dalys_by_scenario = (
    pregnancy_dalys_by_scenario.add(neonatal_ylls_by_scenario, fill_value=0)
    .add(non_pregnancy_anemia_ylds_by_scenario, fill_value=0)
    .add(neural_tube_defect_ylls_by_scenario, fill_value=0)
)
dalys_by_scenario

scenario      entity              wealth_quintile
baseline      anemia              1                  1.108193e+06
                                  2                  9.489557e+05
                                  3                  8.128023e+05
                                  4                  7.438514e+05
                                  5                  5.346643e+05
              lbwsg               1                  1.689969e+07
                                  2                  1.695210e+07
                                  3                  1.391306e+07
                                  4                  1.148816e+07
                                  5                  9.796241e+06
              maternal_disorders  1                  5.115552e+05
                                  2                  5.668783e+05
                                  3                  3.446606e+05
                                  4                  2.881123e+05
                                  5                  2.390688e+05
              ntd                 1                  4.141484e+05
                                  2                  4.234925e+05
                                  3                  3.833772e+05
                                  4                  3.398251e+05
                                  5                  2.984747e+05
intervention  anemia              1                  9.555314e+05
                                  2                  8.058745e+05
                                  3                  6.840081e+05
                                  4                  6.221299e+05
                                  5                  4.396906e+05
              lbwsg               1                  1.678516e+07
                                  2                  1.687010e+07
                                  3                  1.384860e+07
                                  4                  1.146179e+07
                                  5                  9.772947e+06
              maternal_disorders  1                  4.821632e+05
                                  2                  5.415725e+05
                                  3                  3.342310e+05
                                  4                  2.781463e+05
                                  5                  2.256071e+05
              ntd                 1                  1.453895e+05
                                  2                  1.582956e+05
                                  3                  1.756911e+05
                                  4                  1.758600e+05
                                  5                  1.622224e+05
zero          anemia              1                  1.108193e+06
                                  2                  9.489557e+05
                                  3                  8.128023e+05
                                  4                  7.438514e+05
                                  5                  5.346643e+05
              lbwsg               1                  1.689969e+07
                                  2                  1.695210e+07
                                  3                  1.391306e+07
                                  4                  1.148816e+07
                                  5                  9.796241e+06
              maternal_disorders  1                  5.115552e+05
                                  2                  5.668783e+05
                                  3                  3.446606e+05
                                  4                  2.881123e+05
                                  5                  2.390688e+05
              ntd                 1                  4.141484e+05
                                  2                  4.234925e+05
                                  3                  3.833772e+05
                                  4                  3.398251e+05
                                  5                  2.984747e+05
Name: value, dtype: float64

In [25]:
import pathlib

In [26]:
path = f"./results/{location}/{vehicle}/dalys_by_scenario.csv"
pathlib.Path(path).parent.mkdir(exist_ok=True, parents=True)
dalys_by_scenario.to_csv(path)